CREATE TABLE pessoa
(
    id   INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    cpf  VARCHAR(11)  NOT NULL,
    nome VARCHAR(250) NOT NULL
);

CREATE TABLE produto
(
    id             INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    descricao      VARCHAR(50)    NOT NULL,
    valor_unitario NUMERIC(10, 2) NOT NULL
);


